/** Test-only fixture loader — real /api/simulate captures generated by
 * scripts/recon-fixtures/generate_fixtures.py (backend TestClient, pinned
 * heads in RECON_SCEN_REPORT.md T0). Loaded with fs, not `import`, so the
 * ~87KB JSON literals never enter the TS program. */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import type { SimulateRequest, SimulateResponse } from "../../api/simulate-dto";

export interface ReconFixture {
  request: SimulateRequest;
  response: SimulateResponse;
}

/** cwd-based (vitest runs from the repo root): import.meta.url is rebased
 * under the jsdom environment and resolves off-tree there. */
const FIXTURE_DIR = join(process.cwd(), "src", "features", "simulation", "lib", "recon", "__fixtures__");

export function loadFixture(name: "linear" | "shaped" | "settlement"): ReconFixture {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, `${name}.json`), "utf-8")) as ReconFixture;
}

/** Structured clone for fixture mutation in regime tests. */
export function cloneFixture(f: ReconFixture): ReconFixture {
  return JSON.parse(JSON.stringify(f)) as ReconFixture;
}
