/**
 * N1 identity-pin golden config — an owner-representative scenario exercising
 * EVERY request-shaping param: nonzero target + all tenor/credit/IRS spreads,
 * touched intermediate waypoints, two 금통위 events, non-default σ,
 * fundingStepping on, explicit funding rate, one position, real-shaped
 * irsParRates and dailyShockCurves.
 *
 * The committed fixture `__fixtures__/n1-golden-request.json` was generated by
 * running the PRE-N1 buildSimulateRequest (worktree base 2c0311f) over exactly
 * this config. The identity pin asserts the POST-N1 builder reproduces it
 * byte-for-byte with anchorTenor "3Y" (and absent) — the owner's mandated
 * backward-compatibility proof. Regenerate ONLY from a pre-N1 checkout.
 */
import type { ScenarioParams, SimulationInputs } from "../types/simulation-port";

export const N1_GOLDEN_INPUTS: SimulationInputs = {
  positions: [
    {
      id: "GOLDEN-1",
      name: "00000/KRW/260109-310109/3.1250/IRS/REC",
      notional: 10_000_000_000,
      rate: 3.125,
      startDate: "2026-01-09",
      endDate: "2031-01-09",
      direction: "receive",
    } as unknown as SimulationInputs["positions"][number],
  ],
  baseDate: "2026-07-14",
  fundingRate: 2.85,
  dailyShockCurves: { bondCurves: {}, swapCurve: [] },
  irsParRates: [
    { tenor: 1, rate: 2.7 },
    { tenor: 3, rate: 2.75 },
    { tenor: 5, rate: 2.8 },
    { tenor: 10, rate: 2.9 },
  ] as unknown as SimulationInputs["irsParRates"],
};

export const N1_GOLDEN_PARAMS: ScenarioParams = {
  simDays: 180,
  baseShockBp: "30",
  waypoints: [
    { day: 0, bp: 0 },
    { day: 45, bp: 18 },
    { day: 120, bp: 22 },
    { day: 180, bp: 30 },
  ],
  spread1y: "-5",
  spread10y: "12",
  spread30y: "18",
  creditSpreads: { 특은채: "3", 은행채: "4", 카드채: "7", 회사채: "9" },
  irsSpread: "4",
  shortEndEvents: [
    { id: 0, date: "2026-08-27", shiftBp: "-25" },
    { id: 1, date: "2026-11-26", shiftBp: "-25" },
  ],
  sigmaBp: "3.5",
  fundingStepping: true,
  touchedWaypointDays: [45, 120],
};
